<?php get_header();
$category_data = get_term_meta( $cat, '_custom_category_options', true );
$category_type=$category_data['cat_layout'];
$cat_name_show=$category_data['cat_name_show'];
if($category_type == 'list1' ) : include( 'template-parts/list-1.php' );
elseif($category_type == 'list2') : include( 'template-parts/list-2.php' );
elseif($category_type == 'list3') : include( 'template-parts/list-3.php' );
elseif($category_type == 'list4') : include( 'template-parts/list-4.php' );
else : include( 'template-parts/list-1.php' );
endif;
get_footer(); 